CREATE TABLE IF NOT EXISTS `gem_tenders` (
  `id` int NOT NULL AUTO_INCREMENT,
  `page_no` int DEFAULT NULL,
  `bid_number` varchar(100) NOT NULL,
  `detail_url` text,
  `items` text,
  `quantity` varchar(50) DEFAULT NULL,
  `department` text,
  `start_date` varchar(50) DEFAULT NULL,
  `end_date` varchar(50) DEFAULT NULL,
  `ra_no` varchar(255) DEFAULT NULL,
  `ra_url` text,
  `Representation_json` json DEFAULT NULL,
  `Corrigendum_json` json DEFAULT NULL,
  `emd_amount` varchar(50) DEFAULT NULL,
  `bid_value` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `relevance` tinyint(1) DEFAULT '0',
  `relevance_score` float DEFAULT '0',
  `match_count` int DEFAULT '0',
  `match_relevency` float NOT NULL,
  `matches` text,
  `matches_status` enum('Yes','No') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'No',
  `MainRelevencyModelStatus` enum('Yes','No') NOT NULL DEFAULT 'No',
  `relevency_result` tinyint(1) DEFAULT '0',
  `main_relevency_score` float DEFAULT '0',
  `dept` varchar(255) DEFAULT NULL,
  `is_interested` tinyint(1) DEFAULT '0',
  `gpt_match` enum('yes','no','doubt','') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `gpt_dept` varchar(50) DEFAULT NULL,
  `gpt_compliance` json DEFAULT NULL,
  `keyword` varchar(255) DEFAULT NULL,
  `json_data` json NOT NULL,
  `emd_detail` json DEFAULT NULL,
  `consignee_detail` json DEFAULT NULL,
  `sample_req` json DEFAULT NULL,
  `hard_copy_req` json DEFAULT NULL,
  `perfect_cat` int DEFAULT '0',
  `sub_cat` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bid_number` (`bid_number`),
  KEY `idx_gem_created` (`created_at`),
  KEY `idx_bid_number` (`bid_number`),
  KEY `idx_department` (`department`(50))
);


CREATE TABLE IF NOT EXISTS `tender_processing_results` (
  `id` int NOT NULL AUTO_INCREMENT,
  `bid_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `result` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'no',
  `tender_title` text,
  `relevancy_check` json DEFAULT NULL,
  `suggested_products` json DEFAULT NULL,
  `deviation_tables` json DEFAULT NULL,
  `processing_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` varchar(50) DEFAULT 'completed',
  `atc` json DEFAULT NULL,
  `representation_letter` longtext,
  `representation_data` json DEFAULT NULL,
  `representation_generated_at` datetime DEFAULT NULL,
  `main_relevency_score` decimal(5,2) DEFAULT NULL,
  `match_score` decimal(5,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bid_no` (`bid_number`),
  KEY `idx_bid_no` (`bid_number`),
  KEY `idx_processing_date` (`processing_date`)
);